name: Create release branch

on: 
  workflow_dispatch:
   inputs:
    versionName: 
      required: true
      description: 'Enter the new version number'

jobs:
  createrelease:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      # - name: Create release branch
      #   run: git checkout -b release/v${{ github.event.inputs.versionName }}
      - name: Push branch
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: | 
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch --all
          grep version package.json
          git checkout -B release/v${{ github.event.inputs.versionName }} origin/develop
          git merge origin/main
          npm version ${{ github.event.inputs.versionName }}
          grep version package.json
          git push origin release/v${{ github.event.inputs.versionName }}
  createpullrequest:
    needs: [createrelease]
    runs-on: ubuntu-18.04
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: release branch created
          title: v${{ github.event.inputs.versionName }} into main
          body: Release branch created by workflow
          branch: release/v${{ github.event.inputs.versionName }}
          base: main
